### ISSUE TITLE
Reply to bullet #74

### ISSUE THREAD

**Issue by maxnordlund** [essen/essen.github.io#1]
(I'm sorry for hjicking your GH pages repo like this, but since you archived the bullet repo I couldn't reply there.)

While I do agree that most, if not all, browsers support WebSockets now days, it is not the only reason to use a library that can fall back to long polling. For example when using a CDN, or other proxy, that don't support WS going through it.

My suggestion is not not only archived the repo, but also do one final commit to update the README saying so (and maybe merge my PR that fixes funky substitutions for urls with `ws` in them, like `ws.example.com` -> `http.example.com`).

https://github.com/ninenines/bullet/pull/74

**Comment by essen** [comment]
Yes I understand there are still cases where it could be useful. But we're talking edge cases here, especially in an age where everything goes through TLS connections.

I have not had a need for this for quite a long time now and I don't really have time to maintain it (as the recent years should have made clear). If you or someone else wants to take over I will happily put a link to the maintained repo.

**Comment by maxnordlund** [comment]
> I have not had a need for this for quite a long time now and I don't really have time to maintain it (as the recent years should have made clear).

OK, I totally understand, but please add something to the README then.

>  If you or someone else wants to take over I will happily put a link to the maintained repo.

Like you I don't have the time or energy for maintaining bullet I'm afraid. But if the repo is archived you can't open issues anymore (which makes sense), so you need some other way of contacting you. That should also go in the README, yes?

Thanks for all the hard work, and I hope to see more of what you write in the future.
